name: CI/CD Vercel

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    #- name: Install dependencies comentadas por no detener su ejecucion
     # run: npm install
  
    - name: Verify dependencies
      run: npm ls
      
    - name: Run tests
      run: npm test

    - name: Deploy to Vercel
      run: npm install -g vercel && vercel --prod --token ${{ secrets.SECRET_TOKEN }} --yes
